name: Code Quality & Security

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type checking
        run: npx tsc --noEmit
        continue-on-error: true

      - name: ESLint
        run: npm run lint
        continue-on-error: true

      - name: Build check
        run: npm run build
        env:
          NODE_ENV: production
          # Mock environment variables for build-time static analysis
          DATABASE_URL: "postgresql://mock:mock@localhost:5432/mock"
          POSTGRES_URL: "postgresql://mock:mock@localhost:5432/mock"
          KV_REST_API_URL: "https://mock.upstash.io"
          KV_REST_API_TOKEN: "mock"
          BLOB_READ_WRITE_TOKEN: "mock"
          AUTH_SECRET: "mock-secret-for-build-only"
          JWT_SECRET: "mock-jwt-secret-for-build-only"
          WORLD_APP_ID: "mock-app-id"
          NEXT_PUBLIC_APP_ID: "mock-app-id"
          NEXT_PUBLIC_API_URL: "https://mock.example.com"
          AUTH_URL: "https://mock.example.com"

  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=moderate
        continue-on-error: true

      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
        continue-on-error: true

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          allow-licenses: MIT, Apache-2.0, BSD-3-Clause, ISC